baseURL = 'https://olehkondratow.github.io/streamforge-docs/'
languageCode = 'en-us'
title = 'StreamForge Docs'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableGitInfo = true
enableEmoji = true
enableRobotsTXT = true

[module]

  [[module.imports]]
    path = "github.com/McShelby/hugo-theme-relearn"

  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[params]
 ordersectionsby = "weight" 
 showVisitedLinks = true
 disableLandingPageButton = False
 disableNextPrev = false



  [params.branding]
    logoLight = "images/sf-light.png"
    logoDark  = "images/sf-dark.png"

  # Варианты, для которых ИСПОЛЬЗУЕМ светлый логотип:
  lightVariants = ["zen-light", "zen-dark"]

  # Варианты, для которых ИСПОЛЬЗУЕМ тёмный логотип:
  darkVariants = ["relearn-light", "relearn-dark", "relearn-bright", "learn", "neon"]

  # ----- Варианты цветовых тем -----
  [[params.themeVariant]]
    identifier = "relearn-light"

  [[params.themeVariant]]
    identifier = "relearn-dark"

  [[params.themeVariant]]
    identifier = "relearn-bright"

  [[params.themeVariant]]
    identifier = "zen-light"

  [[params.themeVariant]]
    identifier = "zen-dark"

  [[params.themeVariant]]
    identifier = "neon"

  [[params.themeVariant]]
    identifier = "learn"

  [params.social]
    github  = "https://github.com/OlehKondratow"
    linkedin = "https://www.linkedin.com/in/olehkondratow/"

  [params.author]
    name  = "Oleh Kondratow"
    email = "box@okondratov.pl"

  [languages.en]
    title = "StreamForge Docs"

  [languages.ru]
    title = "StreamForge Docs (RU)"

 [languages.pl]
   title = "StreamForge Docs (PL)"

  # Футер сайдбара: история, переключатель темы, языков
  [[params.sidebarfootermenus]]
    identifier = 'footercontrols'
    type = 'custom'
    [[params.sidebarfootermenus.elements]]
      type = 'historyclearer'         # кнопка очистки истории
    [[params.sidebarfootermenus.elements]]
      type = 'variantswitcher'        # селектор цветовой темы
      # icon = 'palette'              # при желании переопределить иконку
    [[params.sidebarfootermenus.elements]]
      type = 'languageswitcher'       # селектор языка

  # Хедер сайдбара: переключатель версий (если настроено versioning)
  [[params.sidebarheadermenus]]
    identifier = 'headercontrols'
    type = 'custom'
    [[params.sidebarheadermenus.elements]]
      type = 'versionswitcher'        # селектор версии
